import logging
from typing import List, Optional, Tuple

from desktop.models.planner_models import ExecutionGoal, WorkflowPlan, WorkflowStep, PlanFailureReason, CapabilityResolution

logger = logging.getLogger(__name__)

class PlannerRuntime:
    """
    Rule 35: Deterministic Planning.
    Rule 25: The Planner produces descriptions, never side effects.
    Given an ExecutionGoal and a list of candidate capabilities, determines HOW to orchestrate fulfillment.
    """
    
    def plan(self, goal: ExecutionGoal, candidates: List[CapabilityResolution]) -> Tuple[Optional[WorkflowPlan], Optional[PlanFailureReason]]:
        logger.info(f"Generating deterministic WorkflowPlan for goal: {goal.action} {goal.target}")
        
        if not candidates:
            logger.error(f"Planning failed: No capabilities provided by CapabilityResolver")
            return None, PlanFailureReason.UNKNOWN_CAPABILITY
            
        # 1. Orchestration Phase (LLM reasoning would go here to chain candidates).
        # For MVP fallback, we just construct a workflow using the first candidate.
        best_candidate = candidates[0]
            
        # 2. Workflow Construction Phase
        step = WorkflowStep(
            capability=best_candidate.capability,
            parameters=best_candidate.parameters,
            dependencies=[]
        )
        
        plan = WorkflowPlan(
            goal_id=goal.session_id,
            steps=[step]
        )
        
        logger.info("WorkflowPlan successfully generated by PlannerRuntime.")
        return plan, None
