from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from datetime import datetime

@dataclass
class KnowledgeSource:
    """A generic source of knowledge (Tab, PDF, File, Memory)."""
    id: str
    type: str
    url: str
    title: str
    author: str
    timestamp: datetime
    # Source Quality Metadata
    authority: float    # Official Docs (100) vs Random Blog (38)
    freshness: float
    bias: float
    trust_score: float
    importance: float
    status: str
    summary: str
    entities: List[str]
    relationships: Dict[str, str]

@dataclass
class ResearchConclusion:
    """Rule 148: Every conclusion preserves traceability."""
    statement: str
    confidence: float
    supporting_sources: List[str]  # IDs of KnowledgeSources
    conflicting_sources: List[str] # IDs of KnowledgeSources

@dataclass
class KnowledgeRevision:
    """Models the evolution of knowledge across sessions."""
    statement: str
    old_confidence: float
    new_confidence: float
    reason: str
    new_evidence: List[str]

@dataclass
class TopicNode:
    name: str
    conclusions: List[ResearchConclusion]
    open_questions: List[str]
    revisions: List[KnowledgeRevision] = field(default_factory=list)

@dataclass
class TopicGraph:
    """Structured reasoning over a knowledge domain."""
    main_topic: str
    subtopics: Dict[str, TopicNode]
    confidence: float

@dataclass
class KnowledgeID:
    """Stable identity for a Knowledge Workspace to allow merging across days."""
    hash_id: str
    topic: str
    entities: List[str]
    time_window: str

@dataclass
class KnowledgeWorkspace:
    """The working context for the Research Assistant."""
    identity: KnowledgeID
    active_topic: str
    sources: List[KnowledgeSource]
    working_notes: str
    knowledge_gaps: List[str]
    hypotheses: List[str]
    questions: List[str]
    confidence: float
    started_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

@dataclass
class KnowledgeArtifact:
    """A distinct artifact generated by the planner, kept separate from persistence."""
    type: str # Summary, Comparison, Decision Matrix, Timeline, FAQ, etc.
    title: str
    sections: Dict[str, str]
    citations: List[str]
    generated_at: datetime = field(default_factory=datetime.now)
    workflow_origin: str = "Research Assistant"

@dataclass
class GapAnalysis:
    """Identifies missing information from the KnowledgeWorkspace."""
    missing_topics: List[str]
    suggested_queries: List[str]
    impact_on_confidence: float

@dataclass
class ResearchMetrics:
    """Telemetry for optimizing research execution."""
    sources_observed: int = 0
    sources_used: int = 0
    duplicates_removed: int = 0
    conflicts_detected: int = 0
    gaps_found: int = 0
    artifact_size: int = 0
    confidence: float = 0.0
    planning_time: float = 0.0
    # Higher level session scores
    coverage_score: float = 0.0 # 0-100% How much of the topic has been explored
    novelty_score: float = 0.0  # 0-100% How much of today's session was new
