from enum import Enum


class AudioState(Enum):
    OFF = "OFF"
    INITIALIZING = "INITIALIZING"
    IDLE = "IDLE"
    WAKE_DETECTED = "WAKE_DETECTED"
    LISTENING = "LISTENING"
    PROCESSING = "PROCESSING"
    RESPONDING = "RESPONDING"
    INTERRUPTED = "INTERRUPTED"
    ERROR = "ERROR"
    SHUTDOWN = "SHUTDOWN"
