from enum import Enum


class InterruptReason(Enum):
    USER_INTERRUPT = "USER_INTERRUPT"
    SYSTEM_INTERRUPT = "SYSTEM_INTERRUPT"
    HIGH_PRIORITY_INTERRUPT = "HIGH_PRIORITY_INTERRUPT"
    ERROR_INTERRUPT = "ERROR_INTERRUPT"
    TIMEOUT_INTERRUPT = "TIMEOUT_INTERRUPT"
