import asyncio
import uuid
from datetime import datetime, timedelta
from desktop.runtimes.memory.timeline import ExperienceTimeline
from desktop.runtimes.memory.models import Episode, StorageTier
from desktop.capabilities.memory_recall import MemoryRecallCapability

class MockAIRuntime:
    pass

async def execute_demo():
    print("--- Memory Integration Demonstration ---\n")
    
    # 1. Initialize Memory Timeline
    timeline = ExperienceTimeline()
    
    # 2. Simulate Past Episodes (Generated by the EpisodeDetector previously)
    now = datetime.now()
    yesterday = now - timedelta(days=1)
    
    e1 = Episode(
        id=str(uuid.uuid4()),
        start_time=yesterday.replace(hour=9, minute=0),
        end_time=yesterday.replace(hour=11, minute=30),
        description="Editing workflow.py and models.py",
        intent="IMPLEMENTING",
        application="Code.exe",
        project="CHITTI",
        importance=0.8,
        confidence=0.95,
        novelty=0.5,
        tier=StorageTier.HOT
    )
    e2 = Episode(
        id=str(uuid.uuid4()),
        start_time=yesterday.replace(hour=11, minute=30),
        end_time=yesterday.replace(hour=12, minute=0),
        description="Reading PyTorch Documentation",
        intent="RESEARCHING",
        application="Chrome.exe",
        project=None,
        importance=0.4,
        confidence=0.90,
        novelty=0.2,
        tier=StorageTier.HOT
    )
    
    timeline.append_episode(e1)
    timeline.append_episode(e2)
    print("Episodes stored in Experience Timeline.")
    
    # 3. Simulate Memory Recall Capability
    print("\nUser asks: 'What was I implementing yesterday?'")
    recall = MemoryRecallCapability(timeline, MockAIRuntime())
    
    answer = await recall.execute({"intent_filter": "IMPLEMENTING"})
    
    print(f"\nCHITTI Recalls: {answer}")

if __name__ == "__main__":
    asyncio.run(execute_demo())
