from enum import Enum

class ProtocolError(Enum):
    INVALID_PROTOCOL = "INVALID_PROTOCOL"
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    INVALID_PATCH = "INVALID_PATCH"
    RENDER_TIMEOUT = "RENDER_TIMEOUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_RENDERER_ERROR = "INTERNAL_RENDERER_ERROR"
