import time
from dataclasses import dataclass, field
from typing import List, Optional, Any, Dict
from datetime import datetime
from enum import Enum
from desktop.models.conversation import EntityDescriptor

class FactStatus(Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

class MemorySource(Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"

class FactSourceType(Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"

class ExperienceLevel(Enum):
    NONE = "NONE"       # Score < 0.40 (Zero-shot LLM planning)
    LOW = "LOW"         # Score 0.40 - 0.59 (Background context hint)
    MEDIUM = "MEDIUM"   # Score 0.60 - 0.74 (Advisory guidance)
    HIGH = "HIGH"       # Score 0.75 - 0.89 (Strongly guided LLM planning)
    EXACT = "EXACT"     # Score >= 0.90 (Deterministic replay path - COG-31E)

@dataclass
class RetrievalConfig:
    """
    COG-31A: Configurable tuning parameters for MemoryRetrievalEngine.
    """
    candidate_pool_limit: int = 50        # Stage 1 max candidate fetch pool limit
    top_k: int = 3                        # Top-K candidate hints projected to snapshot
    min_similarity_threshold: float = 0.40 # Hard pruning threshold
    recency_window_hours: int = 168       # Default 7 days recency window

@dataclass
class ReplayStatistics:
    """
    COG-31F: Operational metadata tracking long-term execution performance of an Episode.
    Stored in MemoryRuntime metadata tables for analytics and retrieval diagnostics.
    Does NOT affect execution or planner decisions directly.
    """
    replay_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    average_latency_ms: float = 0.0
    last_used_timestamp: float = 0.0
    last_success_timestamp: Optional[float] = None

    @property
    def success_rate(self) -> float:
        total = self.success_count + self.failure_count
        return (self.success_count / total) if total > 0 else 0.0

@dataclass
class OptimizationRecommendation:
    """
    COG-31F: Advisory diagnostic recommendation generated by MemoryLearningEngine.
    Exposed to developer logs/analytics. Never mutates runtime configuration automatically.
    """
    recommendation_type: str
    target_component: str
    observation: str
    suggested_value: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    timestamp: float = field(default_factory=time.time)

@dataclass
class MemoryEpisodeHint:
    """
    COG-31B: Pure domain model representing semantic experience information.
    Contains NO prompt formatting, XML generation, database keys, or raw ExecutionPlans.
    """
    intent_summary: str
    verified_outcome: str
    workflow_summary: str
    parameter_summary: Dict[str, Any]
    episode_score: float
    episode_quality: float
    experience_level: ExperienceLevel = ExperienceLevel.MEDIUM
    retrieval_confidence: float = 0.0

@dataclass
class EpisodeScore:
    """
    Phase 3 Contract #7: Dynamic value dictating the priority and confidence of an Episode for replay selection.
    """
    score: float
    last_updated: float
    version: str = "1.0"
    decay_factor: Optional[float] = 1.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "score": self.score,
            "last_updated": self.last_updated,
            "version": self.version,
            "decay_factor": self.decay_factor
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Optional['EpisodeScore']:
        if not data:
            return None
        return cls(
            score=data.get("score", 0.0),
            last_updated=data.get("last_updated", 0.0),
            version=data.get("version", "1.0"),
            decay_factor=data.get("decay_factor", 1.0)
        )

@dataclass
class EpisodeQuality:
    """
    Phase 3 Contract #8: Quantitative evaluation of an episode's execution value.
    """
    latency_ms: float
    accuracy_confidence: float
    version: str = "1.0"
    user_feedback_score: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "latency_ms": self.latency_ms,
            "accuracy_confidence": self.accuracy_confidence,
            "version": self.version,
            "user_feedback_score": self.user_feedback_score
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Optional['EpisodeQuality']:
        if not data:
            return None
        return cls(
            latency_ms=data.get("latency_ms", 0.0),
            accuracy_confidence=data.get("accuracy_confidence", 0.0),
            version=data.get("version", "1.0"),
            user_feedback_score=data.get("user_feedback_score")
        )

@dataclass
class Episode:
    """
    Phase 3 Contract #6: Ultimate, immutable record coupling Intent, Execution, and Verification.
    Acts as the basic unit of CHITTI's experience.
    """
    episode_id: str
    intent: Any
    execution_plan: Any
    execution_trace: Any
    verification_result: Any
    fingerprint: Any
    timestamp: float
    version: str = "1.0"
    episode_score: Optional[EpisodeScore] = None
    episode_quality: Optional[EpisodeQuality] = None

    def to_dict(self) -> Dict[str, Any]:
        plan_dict = None
        if self.execution_plan:
            if hasattr(self.execution_plan, "to_dict"):
                plan_dict = self.execution_plan.to_dict()
            elif isinstance(self.execution_plan, dict):
                plan_dict = self.execution_plan
            else:
                workflows_serialized = []
                for wf in getattr(self.execution_plan, "workflows", []):
                    workflows_serialized.append({
                        "action": getattr(wf, "action", ""),
                        "correlation_id": getattr(wf, "correlation_id", ""),
                        "parameters": getattr(wf, "parameters", {}) or {}
                    })
                plan_dict = {
                    "schema_version": "1.0",
                    "planner_version": "1.0.0-deterministic",
                    "runtime_version": "3.0",
                    "decision_quality": getattr(getattr(self.execution_plan, "decision_quality", None), "value", "CERTAIN"),
                    "workflows": workflows_serialized
                }

        trace_dict = None
        if self.execution_trace:
            if hasattr(self.execution_trace, "to_dict"):
                trace_dict = self.execution_trace.to_dict()
            elif isinstance(self.execution_trace, dict):
                trace_dict = self.execution_trace
            else:
                steps_serialized = []
                for s in getattr(self.execution_trace, "steps", []):
                    steps_serialized.append({
                        "step_id": getattr(s, "step_id", ""),
                        "capability_name": getattr(s, "capability_name", ""),
                        "status": getattr(getattr(s, "status", None), "value", str(getattr(s, "status", ""))),
                        "start_time": getattr(s, "start_time", 0.0),
                        "end_time": getattr(s, "end_time", 0.0),
                        "parameters": getattr(s, "parameters", {}) or {},
                        "output_payload": getattr(s, "output_payload", {}) or {},
                        "error_message": getattr(s, "error_message", None)
                    })
                trace_dict = {
                    "trace_id": getattr(self.execution_trace, "trace_id", ""),
                    "plan_id": getattr(self.execution_trace, "plan_id", ""),
                    "total_duration_ms": getattr(self.execution_trace, "total_duration_ms", 0.0),
                    "overall_status": getattr(getattr(self.execution_trace, "overall_status", None), "value", str(getattr(self.execution_trace, "overall_status", ""))),
                    "version": getattr(self.execution_trace, "version", "1.0"),
                    "steps": steps_serialized
                }

        v_result_dict = None
        if self.verification_result:
            if hasattr(self.verification_result, "to_dict"):
                v_result_dict = self.verification_result.to_dict()
            elif isinstance(self.verification_result, dict):
                v_result_dict = self.verification_result
            else:
                v_result_dict = {
                    "status": getattr(getattr(self.verification_result, "status", None), "value", str(getattr(self.verification_result, "status", ""))),
                    "evidence": getattr(self.verification_result, "evidence", []),
                    "version": getattr(self.verification_result, "version", "1.0")
                }

        fp_dict = None
        if self.fingerprint:
            if hasattr(self.fingerprint, "to_dict"):
                fp_dict = self.fingerprint.to_dict()
            elif isinstance(self.fingerprint, dict):
                fp_dict = self.fingerprint

        return {
            "episode_id": self.episode_id,
            "intent": self.intent if isinstance(self.intent, (dict, str, int, float, list)) else str(self.intent),
            "execution_plan": plan_dict,
            "execution_trace": trace_dict,
            "verification_result": v_result_dict,
            "fingerprint": fp_dict,
            "timestamp": self.timestamp,
            "version": self.version,
            "episode_score": self.episode_score.to_dict() if self.episode_score else None,
            "episode_quality": self.episode_quality.to_dict() if self.episode_quality else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Episode':
        if not data:
            return None
        from desktop.models.environment import EnvironmentFingerprint
        
        score_data = data.get("episode_score")
        quality_data = data.get("episode_quality")
        fp_data = data.get("fingerprint")

        return cls(
            episode_id=data.get("episode_id", ""),
            intent=data.get("intent"),
            execution_plan=data.get("execution_plan"),
            execution_trace=data.get("execution_trace"),
            verification_result=data.get("verification_result"),
            fingerprint=EnvironmentFingerprint.from_dict(fp_data) if isinstance(fp_data, dict) else fp_data,
            timestamp=data.get("timestamp", 0.0),
            version=data.get("version", "1.0"),
            episode_score=EpisodeScore.from_dict(score_data) if isinstance(score_data, dict) else None,
            episode_quality=EpisodeQuality.from_dict(quality_data) if isinstance(quality_data, dict) else None,
        )

@dataclass
class Fact:
    pass

@dataclass(frozen=True)
class MemoryEpisode:
    """
    Immutable canonical long-term storage format for an activity session.
    Generated exactly as received from Activity Intelligence, with no reinterpretation.
    """
    episode_id: str
    activity_type: str
    start_time: datetime
    end_time: datetime
    duration: float
    workspace_hint: Optional[str]
    referenced_entities: List[EntityDescriptor]
    source_activity_id: str
    source_session_id: str
    related_observation_ids: List[str]
    confidence: float


# ---------------------------------------------------------------------------
# Session State (CID-003 Fix — RSM-1)
# ---------------------------------------------------------------------------

class SessionState(Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


# ---------------------------------------------------------------------------
# Interaction Record (CID-003 Fix — RSM-1)
# ---------------------------------------------------------------------------

@dataclass
class InteractionRecord:
    """
    Immutable record of a single conversational turn.
    Stored in MemoryRuntime Layer 4 (conversation_turns table).
    """
    interaction_id: str
    session_id: str
    role: str               # "user" | "assistant"
    content: str
    timestamp: float
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Working Memory Entry (CID-003 Fix — RSM-1)
# ---------------------------------------------------------------------------

@dataclass
class WorkingMemoryEntry:
    """
    Short-lived workflow-scoped memory entry.
    Scoped per workflow_id and key. May have a TTL.
    """
    workflow_id: str
    key: str
    value: Any
    created_at: float
    ttl_seconds: Optional[int] = None


# ---------------------------------------------------------------------------
# Planner-facing Memory Models (CID-003 Fix — RSM-1)
# ---------------------------------------------------------------------------

@dataclass
class FactRecord:
    """A semantic fact held in memory (Layer 2)."""
    id: str
    type: str
    subject: str
    predicate: str
    value: str
    confidence: float
    source_type: str
    status: str
    embedding: Optional[List[float]] = None


@dataclass
class EpisodeRecord:
    """A summarised episode record for planner context."""
    id: str
    timestamp: float
    content: str
    source: str
    correlation_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RelationshipRecord:
    """A knowledge graph relationship."""
    id: str
    source_id: str
    target_id: str
    relationship_type: str


# ---------------------------------------------------------------------------
# Memory Snapshot — Passed to Planner as context (CID-003 Fix — RSM-1)
# Previously this class was imported everywhere but never defined,
# causing the planner to always receive records=[], working_memory={}.
# ---------------------------------------------------------------------------

@dataclass
class MemorySnapshot:
    """
    A point-in-time read-only projection of memory state.
    Built by MemoryRuntime.snapshot() and consumed by PlannerRuntime.
    Provides the planner with its full context: recent interactions,
    active working memory, known facts, episodes, and graph relationships.

    Rule 85: Context is a read-only projection of system state.
    Rule 36: Memory reads are cheap, writes are explicit.
    """
    session_id: str
    workflow_id: str = "global"
    session_state: SessionState = SessionState.ACTIVE
    recent_interactions: List[InteractionRecord] = field(default_factory=list)
    working_memory: List[WorkingMemoryEntry] = field(default_factory=list)
    facts: List[FactRecord] = field(default_factory=list)
    episodes: List[EpisodeRecord] = field(default_factory=list)
    relationships: List[RelationshipRecord] = field(default_factory=list)
    episode_hints: List[MemoryEpisodeHint] = field(default_factory=list)
    # Legacy compatibility fields (used by planner_contracts.py)
    records: List[Any] = field(default_factory=list)
